wikimedia/eslint-plugin-no-jquery

rules/no-event-shorthand.js
tests/no-event-shorthand.js

'hover' will be deprecated along with other event shorthands.

Add 'hover' pseudo-event to no-event-shorthand

---

Changelog.md
package-lock.json
package.json

Release v1.3.2-wmf.6

---

Changelog.md
README.md
index.js
package-lock.json
package.json

Rename package to eslint-plugin-no-jquery

---

package-lock.json
package.json

Reverts wikimedia/eslint-plugin-no-jquery#74
Actually this isn't needed, 5.7.0 is only needed to run eslint-config-wikimedia. This ruleset on its own only needs version 2.

Revert "Correct eslint peerDependency to 5.7.0, lowest required version"

---

Changelog.md
README.md
package-lock.json
package.json

Start at 2.0.0 to avoid a backwards jump in numbering
on our releases page.
Tweak readme and package.json. Minor eslint upate.

Tag 2.0.0: Reset version numbering for new repo name

---

README.md
index.js
rules/no-class-state.js
tests/no-class-state.js

This is a more specific version of 'no-class' that specifically
disallows reading document state from the DOM, which would
be bad pracitce in a model-view application.

Disallow querying the DOM for state using class methods

---

rules/no-parse-html-literal.js
tests/no-parse-html-literal.js

* When argument is a literal tree, evaluate it.
* Lint against HTML literal parsing done by
$.html/add/append methods.

Improvements to no-parse-html-literal

---

.editorconfig

This improves the contributor experience for anyone using an editor supporting EditorConfig (all code editors I know of support it either built-in or through a plugin).
For instance, my IDE is configured to use spaces for indentation by default, as this is the coding standard in my own projects. With this EditorConfig file, it will automatically switch to tabs when working on this project, instead of using spaces until I manually change the config (after figuring it out).

Add an EditorConfig config file

---

rules/no-attr.js
rules/no-data.js
rules/no-text.js
rules/utils.js
tests/no-map-collection.js
tests/no-map-util.js
tests/no-map.js
tests/no-trim.js

When a method returns an Array or a string rather than a jQuery collection, further method calls on it should not be considered as calls to a jQuery collection method.
Fixes #96

Fix the detection of jQuery collection calls for non-fluent APIs

---

docs/no-camel-case.md
docs/no-event-shorthand.md
docs/no-hold-ready.md
docs/no-is-array.md
docs/no-is-numeric.md
docs/no-node-name.md
docs/no-now.md
docs/no-proxy.md
docs/no-type.md
index.js

Added to 3.3:
* `no-event-shorthand`
* `no-is-numeric`
* `no-now`
* `no-proxy`
* `no-type`
Create a 3.2 ruleset:
* `no-hold-ready`
* `no-is-array`
* `no-node-name`
Fixes #117

Update deprecations rulesets

---

docs/no-is-array.md
rules/no-is-array.js
rules/utils.js
tests/no-is-array.js

Create a fixer for no-is-array

---

docs/no-unique.md
rules/no-unique.js
tests/no-unique.js

Create a fixer for no-unique

---

README.md
docs/no-ajax-events.md
docs/no-animate-toggle.md
docs/no-find.md
docs/no-load.md
docs/no-parse-html-literal.md
docs/no-ready.md
docs/no-trim.md
docs/no-variable-name.md
index.js
rule-tester-and-docs.js
rules/no-class-state.js
rules/no-constructor-attributes.js
rules/no-load-shorthand.js
rules/no-on-ready.js
rules/no-sizzle.js
rules/no-variable-name.js
rules/utils.js
tests/no-ajax-events.js
tests/no-animate-toggle.js
tests/no-find.js
tests/no-load.js
tests/no-parse-html-literal.js
tests/no-ready.js
tests/no-trim.js
tests/no-variable-name.js

* Add `hasClass` and `is` to `nonCollectionReturningMethods`
* Special case `data` which returns a collection with two
arguments, or a plain object argument
* Special case `outerWidth`/`outerHeight` which return collections
with two arguments, or a numerical argument
* Assume that utilities don't return a collection
* Assume that new plugin methods don't return a collection

Improvements to collection return detection

---

docs/no-event-shorthand.md
rules/no-event-shorthand.js
test-all/methods.js
tests/no-event-shorthand.js

The rule for `load` is more complex due to the conflict
with the Ajax load method. Use `no-load-shorthand` for
now but in the future we should share the logic of that
rule with this one.

Remove `load` from `no-event-shorthand`

---

package.json
rule-tester-and-docs.js

This speeds up doc generation from 30s to 13s locally.

Use a limited ruleset for lint-fixing documentation snippets

---

tests/variable-pattern.js

Was inherited from an error in the jQuery docs
which I fixed in jquery/api.jquery.com#1155.

Remove incorrect TODO comment

---

docs/no-event-shorthand.md
index.js
rules/no-event-shorthand.js
tests/no-event-shorthand.js

Ajax event shorthands were not deprecated until 3.5.

Add `allowAjaxEvents` option to `no-event-shorthand` and use in `deprecated-3.3`

---

.github/workflows/nodejs.yml
package.json
src/rules/no-ajax-events.js
src/rules/no-animate-toggle.js
src/rules/no-animate.js
src/rules/no-class-state.js
src/rules/no-constructor-attributes.js
src/rules/no-deferred.js
src/rules/no-event-shorthand.js
src/rules/no-extend.js
src/rules/no-global-selector.js
src/rules/no-load-shorthand.js
src/rules/no-on-ready.js
src/rules/no-parse-html-literal.js
src/rules/no-ready.js
src/rules/no-sizzle.js
src/rules/variable-pattern.js
src/utils.js
tools/rule-tester-and-docs.js

* Use ':exit' expressions to workaround eslint/eslint#9101
* Drop support for doc build in older versions
* Drop support for fixing in older versions

Fix ESLint 2.3.0 support

---

README.md
README.md.template
docs/rules/variable-pattern.md
src/index.js
test-self/.eslintrc.json
test-self/all/.eslintrc.json
test-self/recommended/.eslintrc.json
test-self/recommended/test.js

New config: `recommended` just includes `variable-pattern` rule

---

Changelog.md
README.md
README.md.template
src/index.js

Even when no new rules are added. This makes it easier to pick the correct config for your version without having to look up which versions we have configs for.

New config: Create a deprecated-X.X config for every minor release

---

Changelog.md
src/index.js

Unlike `slim` where using an unavailable feature will cause an error, these configs should allow users to remove deprecated code over time.
Fixes #254

Configs: Use 'warn' instead of 'error' in `deprecated-X` and `all` configs

---

docs/rules/variable-pattern.md
src/rules/variable-pattern.js
src/utils.js
tests/rules/variable-pattern.js

Previously testing `$div` in `foo($div)` would return `false`
as it assumed that if `$div`'s parent node was a `CallExpression`,
that `$div` was the node being invoked, and so only returned
`true` iff the jQuery constructor was detected.
Add in a `node.parent.calleee = node` check to fix this.
Add some extra unit tests to variable-pattern, although none
of these excercise the new check.

utils.isjQuery: Improve `Identifier` detection

---

docs/rules/no-append-html.md
src/rules/no-append-html.js
tests/rules/no-append-html.js

One would usually pass an existing DOM node to these
methods, but passing an HTML string is supported, so
we should check for it.

no-append-html: Check appendTo/prependTo

---

README.md
docs/rules/no-extend.md
src/rules/no-extend.js
tests/rules/no-extend.js

Replaces $.extend with Object.assign if the first argument
is not literal true.

Implement a fixer for no-extend rule

---

docs/rules/no-append-html.md
src/rules/no-append-html.js
tests/rules/no-append-html.js

- **code: Make isHtmlString a util**
- **Rule fix: `no-append-html`: Allow passing selectors to some methods**

Rule fix: `no-append-html`: Allow passing selectors to some methods

---

docs/rules/no-extend.md
src/rules/no-extend.js
tests/rules/no-extend.js

If the first argument is a variable which could be null
or undefined, then Object.assign will throw.
We could convert to `Object.assign( foo || {}, ... )` but in
most cases this is unnecessary, so probably better to leave
it to users to fix manually.

Rule fix: `no-extend`: Only fix if first arg is object literal

---

docs/rules/no-animate.md
src/rules/no-animate.js
tests/rules/no-animate.js

These are core animation methods that aren't covered in
any other animation rules (e.g. `no-fade`).

Rule fix: Add `stop` and `finish` methods to `no-animate`

---

docs/rules/no-animate.md
src/rules/no-animate.js
tests/rules/no-animate.js

We can't tell what type of animation is being stopped, so assume
it is an allowed scroll.

Rule fix: In `no-animate` allow `stop` and `finish` when `allowScroll`
