wikimedia/eslint-plugin-no-jquery

Changelog.md
package-lock.json
package.json

Tag v1.3.2-wmf.1

---

README.md
index.js
rules/no-global-selector.js
tests/no-global-selector.js

Implement no-global-selector rule

---

README.md
index.js
rules/no-parse-html-literal.js
tests/no-parse-html-literal.js

Introduce no-parse-html-literal

---

README.md
index.js
rules/no-and-self.js
tests/no-and-self.js

Deprecated in favour of no-add-back

Introduce no-and-self rule

---

README.md
index.js
rules/no-bind.js
rules/no-unbind.js
tests/no-bind.js
tests/no-unbind.js

Introduce no-unbind rule

---

README.md
index.js

Also, update the "all" profile for the recently-added rules.
Fixes #16.

Provide version-specific deprecation profiles

---

README.md
index.js
rules/no-animate-toggle.js
tests/no-animate-toggle.js

Introduce no-animate-toggle rule

---

Changelog.md
package.json

Release v1.3.2-wmf.5

---

rules/utils.js
tests/no-clone.js
tests/no-event-shorthand.js

Fix isjQuery util to match $-prefixed properties

---

README.md
index.js
rules/no-fx-interval.js
tests/no-fx-interval.js

Add rule for no-fx-interval and include in deprecated-3.0

---

package-lock.json
package.json

Also minor bump to devDependency.

Correct eslint peerDependency to 5.7.0, lowest required version

---

README.md
rules/no-animate.js
tests/no-animate.js

Add 'allowScroll' option on no-animate rule

---

README.md

Change `jquery` with `no-jquery` in `README.md`.

Fix plugin name in README.md

---

rules/no-load-shorthand.js
rules/no-ready.js
rules/utils.js
tests/no-load-shorthand.js
tests/no-ready.js

Support arrow functions

---

README.md
index.js
rules/no-constructor-attributes.js
tests/no-constructor-attributes.js
tests/no-parse-html-literal.js

Introduce no-constructor-attributes rule

---

README.md
index.js
rules/no-sizzle.js
tests/no-sizzle.js

Separate out positional sizzle selectors and add to deprecated-3.4

---

docs/no-is-empty-object.md
docs/no-is-plain-object.md
index.js
rules/no-is-empty-object.js
rules/no-is-plain-object.js
tests/no-is-empty-object.js
tests/no-is-plain-object.js

Introduce no-is-empty-object and no-is-plain-object

---

docs/no-camel-case.md
index.js
rules/no-camel-case.js
tests/no-camel-case.js

Add rule for the deprecation of jQuery.camelCase

---

docs/no-contains.md
rules/no-contains.js
tests/no-contains.js

Add a rule forbidding the $.contains utility

---

docs/no-parse-json.md
rules/no-parse-json.js
tests/no-parse-json.js

Add fixer for no-parse-json

---

rules/no-and-self.js
rules/utils.js
tests/no-and-self.js

Add fixer for no-and-self

---

docs/no-contains.md
docs/no-error.md
rules/no-error.js
tests/no-contains.js
tests/no-error.js

Introduce `no-error` rule

---

docs/no-clone.md
rules/no-clone.js
tests/no-clone.js

Include the `$.clone` utility in the `no-clone` rule

---

README.md
docs/no-variable-name.md
index.js
rule-tester-and-docs.js
rules/no-variable-name.js
tests/no-variable-name.js

Introduce `no-variable-name` rule

---

README.md
package.json

Add `npm run testpath` for running a single test

---

docs/no-parse-html-literal.md
rules/no-parse-html-literal.js
tests/no-parse-html-literal.js

Enforce single tag style in `no-parse-html-literal`

---

README.md
docs/no-hide.md
docs/no-show.md
docs/no-toggle.md
docs/no-visibility.md
index.js
rule-tester-and-docs.js
rules/no-hide.js
rules/no-show.js
rules/no-toggle.js
rules/no-visibility.js
test-all/methods.js
tests/no-visibility.js

Introduce `no-visibility`, deprecate `no-show`, `no-hide`, `no-toggle`

---

docs/no-ajax-events.md
docs/no-ajax.md
docs/no-animate-toggle.md
docs/no-animate.md
docs/no-fade.md
docs/no-load.md
docs/no-parse-xml.md
docs/no-slide.md
index.js

Create profile for jQuery slim build

---

.github/workflows/nodejs.yml

Check documentation in CI

---

rule-tester-and-docs.js

Check rules are listed in README.md & index.js

---

rules/no-and-self.js
rules/no-error-shorthand.js
rules/no-event-shorthand.js
rules/no-hide.js
rules/no-is-array.js
rules/no-noop.js
rules/no-now.js
rules/no-parse-json.js
rules/no-show.js
rules/no-size.js
rules/no-toggle.js
rules/no-unique.js
rules/no-unload-shorthand.js
rules/utils.js
tests/no-hide.js
tests/no-show.js
tests/no-toggle.js

* Pass 'deprecated' options to createRule
* Show deprecation message in linting error

Show deprecation message in linting error

---

docs/no-bind.md
docs/no-die.md
docs/no-live.md
docs/no-unbind.md
docs/no-undelegate.md
index.js
rules/no-bind.js
rules/no-die.js
rules/no-live.js
rules/no-unbind.js
rules/no-undelegate.js
test-all/methods.js
tests/no-bind.js
tests/no-die.js
tests/no-unbind.js
tests/no-undelegate.js

Merges:
* no-die -> no-live
* no-unbind -> no-bind
* no-undelegate -> no-delegate
Part of #163

Merge event unbinding rules in binding rules and deprecate

---

docs/no-is-function.md
rules/no-is-function.js
tests/no-is-function.js

Add fixer for `no-is-function`

---

rules/no-global-selector.js
tests/no-global-selector.js

no-global-selector: Explain restriction more clearly

---

docs/no-delegate.md
rules/no-delegate.js
test-all/methods.js

Follow-up #186: Actually merge `no-undelegate` into `no-delegate`

---

README.md
docs/variable-pattern.md
rules/utils.js
tests/variable-pattern.js

Add specification of plugin return types to settings

---

.github/workflows/nodejs.yml
README.md
README.md.template
build-readme.js
package.json
rule-tester-and-docs.js

Docs: Build lists in README.md automatically

---

README.md
docs/no-find-collection.md
docs/no-find-util.md
index.js
rules/no-find-collection.js
rules/no-find-util.js
test-all/methods.js
test-all/utils.js
tests/no-find-collection.js
tests/no-find-util.js

`no-find-util` is being considered for removal in jQuery 4.
Part of #3

Split `no-find` into `no-find-collection` and `no-find-util`

---

README.md
README.md.template
docs/no-trim.md
index.js

Add `no-trim` to new `deprecated-3.5` config

---

Changelog.md
package-lock.json
package.json

Release 2.4.0

---

Changelog.md
package-lock.json
package.json

Release 2.4.1

---

.eslintignore
docs/no-and-self.md
docs/no-error-shorthand.md
docs/no-load-shorthand.md
docs/no-unload-shorthand.md
package-lock.json
package.json
src/rules/no-size.js
src/utils.js
tests/rules/no-and-self.js
tests/rules/no-error-shorthand.js
tests/rules/no-load-shorthand.js
tests/rules/no-unload-shorthand.js

Fix new RuleTester requirements:
* Replace start/end with range[0]/[1]
* Add 'output' to all fixed test cases

Add ESLint 7.0.0 support

---

Changelog.md

There are no feature changes yet, so no need to do a release.

Update Changelog for next release

---

Changelog.md
README.md
docs/rules/no-jquery-constructor.md
docs/rules/no-ready-shorthand.md
docs/rules/no-ready.md
src/index.js
src/rules/no-jquery-constructor.js
test-self/all/constructor.js
test-self/all/methods.js
tests/rules/no-jquery-constructor.js

New rule: `no-jquery-constructor`

---

docs/rules/no-parse-xml.md
src/rules/no-parse-xml.js
tests/rules/no-parse-xml.js

Rule fix: Add fixer for no-parse-xml

---

docs/rules/no-error.md
src/rules/no-error.js
tests/rules/no-error.js

Also fix copy/paste error in valid cases.
Part of #115

Add fixer for no-error

---

docs/rules/no-ready-shorthand.md
src/rules/no-ready-shorthand.js
tests/rules/no-ready-shorthand.js

Add fixer for no-ready-shorthand

---

.eslintrc.json
docs/rules/no-on-ready.md
src/rules/no-on-ready.js
tests/rules/no-on-ready.js

Rule fix: Add fixer for no-on-ready

---

docs/rules/no-proxy.md
src/rules/no-and-self.js
src/rules/no-error.js
src/rules/no-escape-selector.js
src/rules/no-is-array.js
src/rules/no-is-function.js
src/rules/no-load-shorthand.js
src/rules/no-noop.js
src/rules/no-now.js
src/rules/no-parse-json.js
src/rules/no-parse-xml.js
src/rules/no-proxy.js
src/rules/no-ready-shorthand.js
src/rules/no-size.js
src/rules/no-unique.js
src/utils.js
tests/rules/no-proxy.js

Add fixer for no-proxy 

---

src/all-methods.js
tools/build-all-methods.js

Fix comment syntax in build-all-methods.js

---

docs/rules/no-append-html.md
src/rules/no-append-html.js
tests/rules/no-append-html.js

`no-append-html`: Catch `.add(html)`

---

Changelog.md
package-lock.json
package.json

Release v3.0.0
